POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "username": "dany",
    "password": "1234"
}

###

POST http://localhost:3000/users/notes/add
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRhbnkiLCJzdWIiOjEsImlhdCI6MTU4MDU1MDUzNiwiZXhwIjoxNTgwNTUwNTk2fQ.tf1nbYQz_SSlgw17UbumR-AdbFoKoWMCi_87t-ZHrN8

{
    "text": "ewqe",
    "title": "dfdsfds"
}


###

PUT http://localhost:3000/notes/19/tags/add
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRhbnkiLCJzdWIiOjEsImlhdCI6MTU4MDU1MzUyOSwiZXhwIjoxNTgwNzY5NTI5fQ.C7ck_hLCtuMx7sUSXwQ65ZepLwlvHP3pRDKhv7Q5I48

{
    "name": "dans"
}

###

POST http://localhost:3000/notes/19/likes/add
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRhbnkiLCJzdWIiOjEsImlhdCI6MTU4MDU1MzUyOSwiZXhwIjoxNTgwNzY5NTI5fQ.C7ck_hLCtuMx7sUSXwQ65ZepLwlvHP3pRDKhv7Q5I48

{
    "tab": "1"
}