POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "username": "danys",
    "password": "12345"
}

###

POST http://localhost:3000/users/register
Content-Type: application/json

{
    "name": "danys",
    "password": "12345",
    "email": "dany@mail.ru"
}
###
POST http://localhost:3000/users/notes/add
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRhbnlzIiwic3ViIjo1LCJpYXQiOjE1ODA2NjE5MjMsImV4cCI6MTU4MDg3NzkyM30.i23D88U5O11ReGNvs0oah3nT0f-DlMxD0yzb8lftVy0

{
    "text": "10",
    "title": "10"
}


###

PUT http://localhost:3000/notes/22/tags/add
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRhbnlzIiwic3ViIjo1LCJpYXQiOjE1ODA2NjE5MjMsImV4cCI6MTU4MDg3NzkyM30.i23D88U5O11ReGNvs0oah3nT0f-DlMxD0yzb8lftVy0

{
    "name": "dans"
}

###

POST http://localhost:3000/notes/22/likes/add
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRhbnlzIiwic3ViIjo1LCJpYXQiOjE1ODA2NjE5MjMsImV4cCI6MTU4MDg3NzkyM30.i23D88U5O11ReGNvs0oah3nT0f-DlMxD0yzb8lftVy0

{
    "tab": "1"
}

###

GET http://localhost:3000/users
